# Acessando Dados do Pysus

Precisamos começar instalando o Pysus na nossa máquina virtual do Colab!

In [3]:
# pip install pysus

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 22.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 kB 25.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 39.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 77.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.2/152.2 kB 17.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 52.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 49.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 57.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.9/38.9 MB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━

Quando concluído, clique no botão "RESTART RUNTIME"

In [1]:
import pandas as pd
import numpy as np
import pysus as sus
from pysus.online_data import SINAN

Utilizando métodos da classe SINAN, podemos retornar uma lista com os nomes das doenças disponíveis e outra com os anos disponíveis de uma determinada doença.

In [3]:
doencas = SINAN.list_diseases()
print(type(doencas))
print(doencas)

<class 'list'>
['Animais Peçonhentos', 'Botulismo', 'Cancer', 'Chagas', 'Chikungunya', 'Colera', 'Coqueluche', 'Contact Communicable Disease', 'Acidentes de Trabalho', 'Dengue', 'Difteria', 'Esquistossomose', 'Febre Amarela', 'Febre Maculosa', 'Febre Tifoide', 'Hanseniase', 'Hantavirose', 'Hepatites Virais', 'Intoxicação Exógena', 'Leishmaniose Visceral', 'Leptospirose', 'Leishmaniose Tegumentar', 'Malaria', 'Meningite', 'Peste', 'Poliomielite', 'Raiva Humana', 'Sífilis Adquirida', 'Sífilis Congênita', 'Sífilis em Gestante', 'Tétano Acidental', 'Tétano Neonatal', 'Tuberculose', 'Violência Domestica', 'Zika']


In [4]:
anos = SINAN.get_available_years('Acidentes de Trabalho')
print(anos)

['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']


Uma vez decididos a doença e o ano que serão utilizados para a visualização, baixamos o arquivo de dados com a função `read_parquet()` do Pandas.

In [5]:
path = SINAN.download('Acidentes de Trabalho', int(anos[1]))
dataframe = pd.read_parquet(path)

O objeto retornado da função é do tipo DataFrame:

In [6]:
print(type(dataframe))
dataframe

<class 'pandas.core.frame.DataFrame'>


TP_NOT ID_AGRAVO DT_NOTIFIC SEM_NOT NU_ANO SG_UF_NOT ID_MUNICIP  \
0          2      Y96    20070104  200701   2007        35     351380   
1          2      Y96    20070127  200704   2007        35     351380   
2          2      Y96    20070131  200705   2007        35     351380   
3          2      Y96    20070128  200705   2007        35     351380   
4          2      Y96    20070123  200704   2007        35     351380   
...      ...       ...        ...     ...    ...       ...        ...   
19720      2      Y96    20071227  200752   2007        35     354870   
19721      2      Y96    20071211  200750   2007        35     354870   
19722      2      Y96    20071210  200750   2007        29     291470   
19723      2      Y96    20071223  200752   2007        29     290840   
19724      2      Y96    20071219  200751   2007        29     290840   

      ID_REGIONA ID_UNIDADE   DT_ACID  ... MUN_ATENDE UNI_ATENDE PART_CORP1  \
0       1332        2086107  20070104  ...     351380                    06   
1       1332        2086107  20070127  ...     351380    2080028         02   
2       1332        2086107  20070131  ...     351380    2080028         06   
3       1332        2086107  20070128  ...     351380    2080028         06   
4       1332        2086107  20070123  ...     351380    2080028         06   
...          ...        ...       ...  ...        ...        ...        ...   
19720   1332        5239869  20070917  ...     354870    5239869         11   
19721   1332        5239869  20071119  ...     354870    2080591         06   
19722   1396        5369746  20070703  ...     291470    2470152         02   
19723   1410        5634369  20071122  ...     290840    2598205         10   
19724   1410        5634369  20070806  ...     292800    2510278         06   

      PART_CORP2 PART_CORP3 CID_LESAO REGIME EVOLUCAO  DT_OBITO CAT  
0                                S68       3        9             1  
1             03                 S06       2        9             1  
2                                S69       2        9             1  
3                                S67       2        9             1  
4                                S68       3        9             1  
...          ...        ...       ...    ...      ...       ...  ..  
19720         99         99      M544      2        2             1  
19721         99         99      S626      2        2             1  
19722         07         08      T932      2        3             1  
19723                            T290      1        3             2  
19724                            S681      2        2             1  

[19725 rows x 54 columns]

Como podemos ver, um DataFrame é um objeto de Python que se assemelha muito a uma tabela. Se pedirmos a propriedade `.shape` de um DataFrame, ela nos retornará uma tupla com as dimensões da tabela. Nesse caso temos 19.725 linhas, e 54 colunas:

In [7]:
dataframe.shape

(19725, 54)

# Manipulando dados de um DataFrame

Para retirar uma única coluna de um DataFrame, o acessamos com colchetes e chamamos a string correspondente ao nome da coluna:

In [8]:
serie = dataframe['CS_SEXO']
serie

0        M
1        F
2        M
3        M
4        M
        ..
19720    F
19721    M
19722    M
19723    M
19724    M
Name: CS_SEXO, Length: 19725, dtype: object

Cada coluna do DataFrame é de um outro tipo especial de Pandas: uma Série.

In [9]:
type(serie)

pandas.core.series.Series

Através da coluna destacada como série, podemos ainda utilizar o NumPy para convertê-la em um Array, e assim manipulá-lo matematicamente.

In [16]:
serie2 = dataframe["PART_CORP2"]
array2 = np.array(serie2)
print(array2.dtype)

object


Porém temos um problema: esse array veio com o mesmo tipo da série, que originalmente era do tipo `object` - o tipo mais genérico do NumPy. Esse tipo abrange a maioria dos conteúdos possíveis, mas não suporta operações matemáticas. 

Podemos tentar fazer uma conversão direta para número:

In [17]:
# array2 = array2.astype("float64")

ValueError: ignored

A célula acima dará um erro, e a mensagem nos diz que não é possível converter as células que possuem uma string vazia para float64. Nesse caso, podemos fazer um leve tratamento: Vamos substituir as strings vazias por zeros.

In [18]:
array2[array2=='  '] = 0
array2 = array2.astype("float64")
array2

array([0., 3., 0., ..., 7., 0., 0.])

Funcionou! Agora que o tipo é numérico, podemos fazer operações matemáticas, como a multiplicação elemento-a-elemento:

In [21]:
array3 = array2 * array2
print(array3.shape)
array3

(19725,)


array([ 0.,  9.,  0., ..., 49.,  0.,  0.])

Para inserir uma coluna nova, podemos acessar o DataFrame com o nome de uma coluna que não existe, e definir nela um array ou série da dimensão correta:

In [22]:
dataframe["COLUNA_NOVA"] = array3

E para remover uma coluna, podemos utilizar o método `.pop()`

In [32]:
dataframe.pop("COLUNA_NOVA")

0           0.0
1           9.0
2           0.0
3           0.0
4           0.0
          ...  
19720    9801.0
19721    9801.0
19722      49.0
19723       0.0
19724       0.0
Name: COLUNA_NOVA, Length: 19725, dtype: float64

# Métodos de acesso em DataFrame

Através do acesso padrão, só conseguimos passar o nome de colunas

In [31]:
dataframe['ID_AGRAVO'] # Só consigo acessar as colunas

0        Y96 
1        Y96 
2        Y96 
3        Y96 
4        Y96 
         ... 
19720    Y96 
19721    Y96 
19722    Y96 
19723    Y96 
19724    Y96 
Name: ID_AGRAVO, Length: 19725, dtype: object

Para acessar linhas, podemos usar a propriedade `.loc`. Com ela, fazemos o acesso através de colchetes, e passamos o NOME do que queremos: primeiro o nome da linha, e depois o nome da coluna. Também podemos passar slices como fazíamos em listas, e se passarmos tanto o nome de uma linha como o de uma coluna, acessamos o exato elemento no cruzamento das duas. 

In [24]:
dataframe.loc[:, "TP_NOT"] # Pelo nome, posso acessar linhas ou colunas

0        2
1        2
2        2
3        2
4        2
        ..
19720    2
19721    2
19722    2
19723    2
19724    2
Name: TP_NOT, Length: 19725, dtype: object

É importante lembrar que os índices das linhas nem sempre são numéricos: assim como as colunas eles podem ser objetos, strings e até números aleatórios. Nesses casos, também temos um método de indexação por posição: a propriedade `.iloc`.

In [33]:
dataframe.iloc[14, 4] # Elemento na 14ª linha, 4ª coluna

'2007'

Com a qual também podemos utilizar slices e índices negativos:

In [34]:
dataframe.iloc[:, -1]

0        1
1        1
2        1
3        1
4        1
        ..
19720    1
19721    1
19722    1
19723    2
19724    1
Name: CAT, Length: 19725, dtype: object

# Métodos de DataFrame

Se quisermos, podemos pedir para um DataFrame uma "lista" com os nomes de suas colunas (na verdade é um objeto do tipo Index, mas pode ser convertido com `list()` e utilizado da mesma forma que uma)

In [35]:
dataframe.keys()

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'ID_UNIDADE', 'DT_ACID', 'SEM_ACID',
       'ANO_NASC', 'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA',
       'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS',
       'ID_OCUPA_N', 'SIT_TRAB', 'NUTEMPO', 'TPTEMPO', 'LOCAL_ACID', 'CNAE',
       'UF_EMP', 'MUN_EMP', 'TERCEIRIZA', 'CNAE_PRIN', 'HORA_ACID', 'MIN_ACID',
       'HORA_JOR', 'MIN_JOR', 'UF_ACID', 'MUN_ACID', 'CID_ACID', 'TIPO_ACID',
       'MAIS_TRAB', 'NU_TRAB', 'ATENDE_MED', 'DT_ATENDE', 'UF_ATENDE',
       'MUN_ATENDE', 'UNI_ATENDE', 'PART_CORP1', 'PART_CORP2', 'PART_CORP3',
       'CID_LESAO', 'REGIME', 'EVOLUCAO', 'DT_OBITO', 'CAT'],
      dtype='object')

Da mesma forma, temos uma propriedade que nos retorna uma lista (nesse caso um array) com os valores definidos como índices do DataFrame.

In [28]:
dataframe.index.values

array([    0,     1,     2, ..., 19722, 19723, 19724])

Por fim, temos uma forma de "simplificar" o DataFrame, retirando os nomes das colunas e os índices personalizados das linhas. Teoricamente, estamos convertendo nossa tabela para uma "matriz" bidimensional, que herda o tipo do DataFrame.

In [29]:
arrayzao = dataframe.values
arrayzao

array([['2', 'Y96 ', '20070104', ..., '        ', '1', 0.0],
       ['2', 'Y96 ', '20070127', ..., '        ', '1', 9.0],
       ['2', 'Y96 ', '20070131', ..., '        ', '1', 0.0],
       ...,
       ['2', 'Y96 ', '20071210', ..., '        ', '1', 49.0],
       ['2', 'Y96 ', '20071223', ..., '        ', '2', 0.0],
       ['2', 'Y96 ', '20071219', ..., '        ', '1', 0.0]], dtype=object)

Podemos tentar converter esse array para um tipo numérico...

In [30]:
# arrayzao = arrayzao.astype("float64") 

ValueError: ignored

Mas novamente teremos um erro, pois temos várias células com letras que não podem ser convertidas para float. Nesse caso seria necessário um tratamento de dados muito mais complexo e exaustivo...

# Armazenando o DataFrame

Para não ser necessário baixar o DataFrame da biblioteca PySus toda vez, podemos salvá-lo em um arquivo de extensão .csv .

In [36]:
dataframe.to_csv('Acidentes de Trabalho.csv', index=False)

Em seguida, podemos ler o csv convertendo-o de volta a um DataFrame.

In [37]:
df = pd.read_csv("Acidentes de Trabalho.csv")

/tmp/ipykernel_3535/1796324158.py:1: DtypeWarning: Columns (17,18,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Acidentes de Trabalho.csv")


# Máscaras em DataFrame

Futuramente, veremos melhor o que significa uma máscara. Por enquanto, entendam a sintaxe abaixo da seguinte forma: Podemos utilizar loc e iloc juntamente com uma condição, e o DataFrame só nos retornará os locais em que essa condição é verdadeira. No exemplo abaixo, estou pedindo primeiro uma condição para as linhas (todas as linhas em que o valor da coluna "ID_MUNICIP" é 351380). Em seguida, passo uma condição para as colunas (nesse caso, só pedi a coluna "CS_GESTANT"). 

In [ ]:
df.loc[df['ID_MUNICIP']==351380, 'CS_GESTANT']

0        6
1        9
2        6
3        6
4        6
        ..
18111    9
18112    6
18113    6
18114    6
18115    6
Name: CS_GESTANT, Length: 137, dtype: int64